(cl:defpackage my_package-srv
  (:use )
  (:export
   "REPUBLISHPOINTCLOUD"
   "<REPUBLISHPOINTCLOUD-REQUEST>"
   "REPUBLISHPOINTCLOUD-REQUEST"
   "<REPUBLISHPOINTCLOUD-RESPONSE>"
   "REPUBLISHPOINTCLOUD-RESPONSE"
  ))

